version: '3.3'
services:

  mysql:
    build: ../images/mysql
    container_name: mysql
    networks: ['data']
    environment:
      - "MYSQL_ROOT_PASSWORD=admin"
    ports:
    - 4000:3306
    volumes:
      - 'mysql:/var/lib/mysql'
      - '/Users/danielspeixoto/datasets/askubuntu/:/custom'

volumes:
  mysql:
    external:
      name: mysql

networks:
  data:
    external:
      name: data
