version: '3.3'
services:
  elasticsearch:
    build: ../images/elasticsearch
    container_name: elasticsearch
    networks: ['elk']
    ports:
    - 9200:9200
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'

  elasticsearch-config:
    build: ../images/elasticsearch-config
    container_name: elasticsearch-config
    networks: ['elk']
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks: ['elk']
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  mysql:
    build: ../images/mysql
    container_name: mysql
    networks: ['data']
    environment:
      - "MYSQL_ROOT_PASSWORD=admin"
    ports:
    - 4000:3306
    volumes:
      - 'mysql:/var/lib/mysql'
      - '/home/daniel/ufba/rec/datasets/stackoverflow/freelancing/:/custom'

  logstash:
    build: ../images/logstash
    container_name: logstash
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks: ['elk', 'data']
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch
      - mysql

networks:
  elk:
  data:

volumes:
  es_data:
  mysql: